# Generated by Django 5.0.1 on 2024-01-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coordinates",
            name="distance",
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
        migrations.AlterField(
            model_name="coordinates",
            name="latitude",
            field=models.DecimalField(decimal_places=5, max_digits=8),
        ),
        migrations.AlterField(
            model_name="coordinates",
            name="longitude",
            field=models.DecimalField(decimal_places=5, max_digits=8),
        ),
    ]
